apiVersion: apps/v1
kind: Deployment
metadata:
  name: openemr
spec:
  replicas: 5
  selector:
    matchLabels:
      io.kompose.service: openemr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: openemr
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysql
              key: host
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql
              key: name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql
              key: username
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        - name: MYSQL_ROOT_PASS
          valueFrom:
            secretKeyRef:
              name: mysql
              key: root_password
        - name: OE_PASS
          value: "pass"
        - name: OE_USER
          value: "admin"
        - name: REDIS_SERVER
          value: "redis"
        - name: SWARM_MODE
          value: "no"
        image: "quay.io/openemr/openemr:latest"
        imagePullPolicy: ""
        name: openemr
        ports:
        - containerPort: 8080
        - containerPort: 8443
        resources: {}
        volumeMounts:
        - mountPath: /var/www/localhost/htdocs/openemr/sites
          name: websitevolume
        - mountPath: /etc/ssl
          name: sslvolume
        - mountPath: /etc/ssl/certs
          name: openemr-certs-1
          readOnly: true
      restartPolicy: Always
      serviceAccountName: openemr
      volumes:
      - name: websitevolume
        persistentVolumeClaim:
          claimName: websitevolume
      - name: sslvolume
        persistentVolumeClaim:
          claimName: sslvolume
      - name: openemr-certs-1
        secret:
          defaultMode: 420
          secretName: openemr-certs
